### ISSUE TITLE
Namespacing items in the $SESSION object

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-gradereport_gradedist#1]
To prevent potential collisions, it might be a good idea to use better namespacing in the $SESSION object. Instead of `$SESSION->gradeitem` something like `$SESSION->gradereport_gradedist_gradeitem` or `$SESSION->gradereport_gradedist->gradeitem` might be safer.

Additionally, I believe you do not need to do `global $SESSION` in scripts like index.php as they are executed in the global context implicitly (unless I miss something).

**Comment by kaspot** [comment]
thanks + added to our todo list

**Comment by mkemmerling** [comment]
Fixed in the master and MOODLE_28_STABLE branches.
