### ISSUE TITLE
Highcharts JS license

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-gradereport_gradedist#3]
As per http://shop.highsoft.com/highcharts.html I assume you intended to use it under its CC-NonCommercial license. However, that is not compatible with GNU GPL so the library cannot be distributed together with your code in a single package. One way would be to remove the js/highcharts.src.js and js/exporting.src.js from your code and let the site admins to download them manually (if they are allowed to - for "personal or non-profit projects"). Alternatively, you may want to search for a library providing same features and is compatible with GPLv3.

**Comment by kaspot** [comment]
thanks - we will take a look at this

**Comment by mkemmerling** [comment]
As proposed the files js/highcharts.src.js and js/exporting.src.js have been removed from the master and MOODLE_28_STABLE branches. A download description has been added to the README.
