### ISSUE TITLE
numerical grade letters

### ISSUE THREAD

**Issue by Marx1st** [academic-moodle-cooperation/moodle-gradereport_gradedist#6]
Hi!

In Germany numericals are used for grading (1 being best, 5 or 6 being failed). In addition to this there are steps in between (1-, 2+, 2-, 3+, etc.).

Theses grade "letters" have been set up in our Moodle (see screenshot), but gradereport_gradedist does display them in incorrect order (see screenshot 2).

The correct order would be: 1, 1-, 2+,2,2-,3+,3,3-,4+,4,5

Regards

![Bildschirmfoto 2019-09-26 um 14 46 55](https://user-images.githubusercontent.com/7048232/65689439-6316b380-e06d-11e9-8951-3b6c6af34f47.png)

![Bildschirmfoto 2019-09-26 um 14 51 25](https://user-images.githubusercontent.com/7048232/65689454-6a3dc180-e06d-11e9-8998-691f68a4cf5d.png)

**Comment by goggo24** [comment]
Thanks for reporting. I could adjust it in our instance too. We will have a look as soon we will find time. If you have ressources to provide us a pull request, we are happy to include it.

**Comment by goggo24** [comment]
Solved in v.3.7.1+ - have fun!
