### ISSUE TITLE
error on latest moodle 4.0

### ISSUE THREAD

**Issue by x0341** [academic-moodle-cooperation/moodle-gradereport_gradedist#9]
Debug info: ERROR: missing FROM-clause entry for table "uf1d_1"
LINE 1: SELECT u.id, u.username, u.idnumber, uf1d_1.data AS profile_...
^
SELECT u.id, u.username, u.idnumber, uf1d_1.data AS profile_field_candidatenumber, uf1d_2.data AS profile_field_group, u.picture, u.firstname, u.lastname, u.firstnamephonetic, u.lastnamephonetic, u.middlename, u.alternatename, u.imagealt, u.email
FROM mdl_user u
JOIN (SELECT DISTINCT eu1_u.id
FROM mdl_user eu1_u
JOIN mdl_user_enrolments ej1_ue ON ej1_ue.userid = eu1_u.id
JOIN mdl_enrol ej1_e ON (ej1_e.id = ej1_ue.enrolid AND ej1_e.courseid = $1)
WHERE 1 = 1 AND eu1_u.deleted = 0) je ON je.id = u.id

JOIN (
SELECT DISTINCT ra.userid
FROM mdl_role_assignments ra
WHERE ra.roleid IN (5)
AND ra.contextid IN ($2,$3,$4)
) rainner ON rainner.userid = u.id
AND u.deleted = 0
ORDER BY u.lastname ASC, u.firstname ASC
[array (
0 => '9',
1 => '1326',
2 => '45',
3 => '1',
)]
Error code: dmlreadexception

Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 1008 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 134 of /grade/report/gradedist/lib.php: call to pgsql_native_moodle_database->get_records_sql()
line 268 of /grade/report/gradedist/lib.php: call to grade_report_gradedist->load_users()
line 127 of /grade/report/gradedist/index.php: call to grade_report_gradedist->load_distribution()

**Comment by goggo24** [comment]
Thanks for reporting. We'll take a look!

**Comment by goggo24** [comment]
Fixed with v.4.0.1 - coming soon.
